apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBP4VwdCFAXuURo0+1KbYLY+mXgTAMGMIckELdq0hd9uUWMqPyghke9GH/53CFIfNHSYGSk24kI8LzZWRgfLzPd10lamtLR95M7stmGpXpORvCVD+kNBBEmaNkDOtF2Hq3y+r6+zCWr1oEn+zqvOJjoWJeJXSXRrSNRoIVDykKBFBIFuDlolrnfSMXjmzGorjc8gXldH2kZ/er6JJ9GlJYyXxb+XW0MtSmAxKcU7+6oF93BTWbKXF/7j4mYykVjFlcBrevXj9Sk8YnKv0GcEFm3wjA3QWIiccRs1LgO+/brZl8b5rdH9KgZ/08JRJBIOwERU2PrZaGcyRuIb36oS+MD6yBk1ldSIQSa0wIivsJpGPW+MbR5kdD+d7yGEgeJMbWWBjmB1mdmw2elCdG7/IbjPN1RK8/84r4SmDcWdu9dLx+TFEY4DPNQBy+6oY/7PvvQHFGQ6FErIsjImKpS4ASthryR4g1RzBKs4Ps00xlfTpeYAlrNFNP04XxyWpuL0o6jG6mD9BXMvzBZtyG0LXpUxCCvvTQT2kvEg7dAuTAlJ/+NfJKycnv89PIYfgvgKeHpLtAYtIWTp/rg65uI04cfsNxo+Eb6f9/qtkKYf1nsz+4W+lGLueO4unPTSxhAVASUaLFKcN1WDXfLcKFbXi9EsF7WlHpuTxedJjTfR+x8Ilo8FIMdJVmGCU4eJ7XH5p34a2DIjI9fkeZQXGDx6oPqUw==
    SECRET_KEY: AgDaO96qR8d1Iwd8lGIlMDkTkxGh5GbnUKhQEIbsi8V76EWV9mUdcKZYbt3wtTxIiXookV3UisJCw8X4ImToRNa5veLwOeBZU/p/dTULthkB+cqmpTlwey5WG7bp2YQ7c1fbtqxFw2NAfZg3+BoWHjXxDrFe1YgIyfomCE1vM10/7pbGKV0xz2tDvVl5EZjjNswXKi/SQHo6sAqXsPAeOLDXhaG8EuE9Z4ykzV1ENTDXCKYwZrPh1DSron+RoWYSOMWKIGmZAdeoiNDgvt/RQByIDasQXsDXIXL+5wPP/da4aE2DWBmlQdrrVClP6z29Cur1vSvp9skZLrN+5BGqyheNRs5cbsYnWcyuiMd8zuAA2/QpLzB6C+ttIA+NM/jOdFqKssecL6rIQ3WKm8JW5K7nW9bMkXEIkfYSLqnWT+elEUGczBCiNsb3OpR9LlafHcR+TAVuNi7VgU8dxOqqCDx8ZsQOFUxxuc2/Uu4wpd1aAtAHxO23NOr/W4R0v9Pcq720bapw13VN9PXcHLO6EMEdOHouAyrPd4t5DGcmcWtuxmAXdEmBGixCQztbxhkHRb3FghnQB6gk9HFmiSJFID402qW+BcxuqAan36SDgb0rRoMeK00EqXQ43GFRF7I3HYw2qV4wU5EaAqGGcS8wOGNdZwQ9/jXqkKcSnF72McTt7JDgkW1e3JvmN/sLR1ssEr1MqGXKrQckx5ZuRENHfqDZnHLfwrYeEdlq+ZzN1G7lMVHvQTikxG59N/YJEg+P99aC0w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

